# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesh.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import point_pb2 as point__pb2
import edge_pb2 as edge__pb2
import triangle_pb2 as triangle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesh.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nmesh.proto\x1a\x0bpoint.proto\x1a\nedge.proto\x1a\x0etriangle.proto\"\xdc\x01\n\x04Mesh\x12!\n\x06points\x18\x01 \x03(\x0b\x32\x11.Mesh.PointsEntry\x12\x14\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x05.Edge\x12\'\n\ttriangles\x18\x03 \x03(\x0b\x32\x14.Mesh.TrianglesEntry\x1a\x35\n\x0bPointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Point:\x02\x38\x01\x1a;\n\x0eTrianglesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.Triangle:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[point__pb2.DESCRIPTOR,edge__pb2.DESCRIPTOR,triangle__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESH_POINTSENTRY = _descriptor.Descriptor(
  name='PointsEntry',
  full_name='Mesh.PointsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Mesh.PointsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Mesh.PointsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=215,
)

_MESH_TRIANGLESENTRY = _descriptor.Descriptor(
  name='TrianglesEntry',
  full_name='Mesh.TrianglesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Mesh.TrianglesEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Mesh.TrianglesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=276,
)

_MESH = _descriptor.Descriptor(
  name='Mesh',
  full_name='Mesh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Mesh.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edges', full_name='Mesh.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triangles', full_name='Mesh.triangles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MESH_POINTSENTRY, _MESH_TRIANGLESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=276,
)

_MESH_POINTSENTRY.fields_by_name['value'].message_type = point__pb2._POINT
_MESH_POINTSENTRY.containing_type = _MESH
_MESH_TRIANGLESENTRY.fields_by_name['value'].message_type = triangle__pb2._TRIANGLE
_MESH_TRIANGLESENTRY.containing_type = _MESH
_MESH.fields_by_name['points'].message_type = _MESH_POINTSENTRY
_MESH.fields_by_name['edges'].message_type = edge__pb2._EDGE
_MESH.fields_by_name['triangles'].message_type = _MESH_TRIANGLESENTRY
DESCRIPTOR.message_types_by_name['Mesh'] = _MESH

Mesh = _reflection.GeneratedProtocolMessageType('Mesh', (_message.Message,), dict(

  PointsEntry = _reflection.GeneratedProtocolMessageType('PointsEntry', (_message.Message,), dict(
    DESCRIPTOR = _MESH_POINTSENTRY,
    __module__ = 'mesh_pb2'
    # @@protoc_insertion_point(class_scope:Mesh.PointsEntry)
    ))
  ,

  TrianglesEntry = _reflection.GeneratedProtocolMessageType('TrianglesEntry', (_message.Message,), dict(
    DESCRIPTOR = _MESH_TRIANGLESENTRY,
    __module__ = 'mesh_pb2'
    # @@protoc_insertion_point(class_scope:Mesh.TrianglesEntry)
    ))
  ,
  DESCRIPTOR = _MESH,
  __module__ = 'mesh_pb2'
  # @@protoc_insertion_point(class_scope:Mesh)
  ))
_sym_db.RegisterMessage(Mesh)
_sym_db.RegisterMessage(Mesh.PointsEntry)
_sym_db.RegisterMessage(Mesh.TrianglesEntry)


_MESH_POINTSENTRY.has_options = True
_MESH_POINTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_MESH_TRIANGLESENTRY.has_options = True
_MESH_TRIANGLESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
