# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: triangle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='triangle.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0etriangle.proto\"I\n\x08Triangle\x12\r\n\x05t_num\x18\x01 \x01(\x05\x12\x0e\n\x06pointA\x18\x02 \x01(\x05\x12\x0e\n\x06pointB\x18\x03 \x01(\x05\x12\x0e\n\x06pointC\x18\x04 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRIANGLE = _descriptor.Descriptor(
  name='Triangle',
  full_name='Triangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t_num', full_name='Triangle.t_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pointA', full_name='Triangle.pointA', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pointB', full_name='Triangle.pointB', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pointC', full_name='Triangle.pointC', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Triangle'] = _TRIANGLE

Triangle = _reflection.GeneratedProtocolMessageType('Triangle', (_message.Message,), dict(
  DESCRIPTOR = _TRIANGLE,
  __module__ = 'triangle_pb2'
  # @@protoc_insertion_point(class_scope:Triangle)
  ))
_sym_db.RegisterMessage(Triangle)


# @@protoc_insertion_point(module_scope)
